name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services with Docker Compose
        run: docker compose up --build -d

      - name: Run Pytest
        run: docker compose exec -T api pytest test_app.py

      - name: Stop Docker Compose
        run: docker compose down
        